"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import {
  getStoredAgentTasks,
  type AgentTask,
  type AgentTaskStatus,
} from "@/lib/api";
import { StatusChip, EmptyStateBlock } from "@/components/ui";
import { PageHeader, StandardPageLayout } from "@/components/workflows";

function ShieldIcon({ className = "h-6 w-6" }: { className?: string }) {
  return (
    <svg className={className} fill="none" stroke="currentColor" viewBox="0 0 24 24">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M12 2L3 7v6c0 5.25 3.75 10 9 11 5.25-1 9-5.75 9-11V7l-9-5z" />
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12l2 2 4-4" />
    </svg>
  );
}

const statusToneMap: Record<AgentTaskStatus, "warning" | "success" | "error" | "info" | "neutral" | "ai"> = {
  pending_review: "warning",
  approved: "success",
  rejected: "error",
  needs_revision: "warning",
  in_progress: "info",
  queued: "neutral",
  bot_reviewing: "ai",
};

function StatusBadge({ status }: { status: AgentTaskStatus }) {
  const labels: Record<AgentTaskStatus, string> = {
    pending_review: "Pending Review",
    approved: "Approved",
    rejected: "Rejected",
    needs_revision: "Needs Revision",
    in_progress: "In Progress",
    queued: "Queued",
    bot_reviewing: "Bot Reviewing",
  };
  return <StatusChip tone={statusToneMap[status]}>{labels[status]}</StatusChip>;
}

type FilterTab = "all" | "pending_review" | "approved" | "rejected" | "needs_revision";

export default function AegisReviewsPage() {
  const params = useParams();
  const projectId = params.id as string;

  const [tasks, setTasks] = useState<AgentTask[]>([]);
  const [filter, setFilter] = useState<FilterTab>("all");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const stored = getStoredAgentTasks(projectId, "aegis");
    setTasks(stored);
    setLoading(false);
  }, [projectId]);

  const filteredTasks = filter === "all" ? tasks : tasks.filter((t) => t.status === filter);
  const pendingCount = tasks.filter((t) => t.status === "pending_review").length;
  const approvedCount = tasks.filter((t) => t.status === "approved").length;
  const rejectedCount = tasks.filter((t) => t.status === "rejected").length;
  const revisionCount = tasks.filter((t) => t.status === "needs_revision").length;

  const filterTabs: { id: FilterTab; label: string; count: number }[] = [
    { id: "all", label: "All", count: tasks.length },
    { id: "pending_review", label: "Pending Review", count: pendingCount },
    { id: "approved", label: "Approved", count: approvedCount },
    { id: "rejected", label: "Rejected", count: rejectedCount },
    { id: "needs_revision", label: "Needs Revision", count: revisionCount },
  ];

  if (loading) {
    return (
      <div className="flex-1 flex items-center justify-center p-10">
        <div className="h-8 w-8 animate-spin rounded-full border-2 border-[var(--brand-primary)] border-t-transparent" />
      </div>
    );
  }

  const breadcrumb = (
    <Link href={`/projects/${projectId}/agents/aegis`} className="inline-flex items-center gap-1 text-[var(--muted)] hover:text-[var(--brand-primary)]">
      <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
      </svg>
      Back to Aegis
    </Link>
  );

  return (
    <StandardPageLayout
      header={
        <PageHeader
          title="Review Queue"
          subtitle="Review scripts generated by Aegis and approve or provide feedback"
          breadcrumb={breadcrumb}
        />
      }
      className="flex-1 p-6 md:p-10 max-w-6xl mx-auto w-full"
    >
      {/* Filter tabs */}
      <div className="flex gap-1 mb-5 border-b border-[var(--border)]">
        {filterTabs.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setFilter(tab.id)}
            className={`px-4 py-2.5 text-sm font-medium border-b-2 transition-colors ${
              filter === tab.id
                ? "border-[var(--brand-primary)] text-[var(--brand-primary)]"
                : "border-transparent text-[var(--muted)] hover:text-[var(--foreground)] hover:border-[var(--border)]"
            }`}
          >
            {tab.label}
            <span className={`ml-1.5 inline-flex items-center justify-center rounded-full px-1.5 py-0.5 text-xs ${
              filter === tab.id
                ? "bg-[var(--brand-primary)]/10 text-[var(--brand-primary)]"
                : "bg-[var(--surface-tertiary)] text-[var(--muted)]"
            }`}>
              {tab.count}
            </span>
          </button>
        ))}
      </div>

      {filteredTasks.length === 0 ? (
        <EmptyStateBlock
          title={filter === "all" ? "No review tasks yet." : `No ${filter.replace("_", " ")} tasks.`}
          description="Run Aegis on test cases to generate scripts for review."
          icon={<ShieldIcon className="h-12 w-12" />}
        />
      ) : (
        <div className="space-y-2">
          {filteredTasks.map((task) => (
            <Link
              key={task.id}
              href={`/projects/${projectId}/agents/aegis/reviews/${task.id}`}
              className="flex items-center gap-4 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4 transition-all hover:border-[var(--brand-primary)] hover:shadow-sm group"
            >
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className="font-mono text-xs text-[var(--muted)]">{task.testcaseExternalId}</span>
                  <StatusBadge status={task.status} />
                  {task.feedback.length > 0 && (
                    <span className="text-xs text-[var(--muted)]">
                      {task.feedback.length} feedback{task.feedback.length > 1 ? "s" : ""}
                    </span>
                  )}
                </div>
                <div className="text-sm font-medium text-[var(--foreground)] group-hover:text-[var(--brand-primary)] truncate">
                  {task.testcaseTitle}
                </div>
                <div className="text-xs text-[var(--muted)] mt-1">
                  {task.completedAt
                    ? `Completed ${new Date(task.completedAt).toLocaleString()}`
                    : `Created ${new Date(task.createdAt).toLocaleString()}`}
                  {task.duration ? ` · ${(task.duration / 1000).toFixed(1)}s` : ""}
                </div>
              </div>
              <div className="flex items-center gap-2 shrink-0">
                {task.script && (
                  <span className="inline-flex items-center gap-1 rounded-full bg-[var(--surface-tertiary)] px-2.5 py-1 text-xs text-[var(--muted)]">
                    <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
                    </svg>
                    Script
                  </span>
                )}
                {task.videoPath && (
                  <span className="inline-flex items-center gap-1 rounded-full bg-[var(--surface-tertiary)] px-2.5 py-1 text-xs text-[var(--muted)]">
                    <svg className="h-3.5 w-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 10l4.553-2.276A1 1 0 0121 8.618v6.764a1 1 0 01-1.447.894L15 14M5 18h8a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v8a2 2 0 002 2z" />
                    </svg>
                    Video
                  </span>
                )}
                <svg className="h-5 w-5 text-[var(--muted)] group-hover:text-[var(--brand-primary)] transition-colors" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </div>
            </Link>
          ))}
        </div>
      )}
    </StandardPageLayout>
  );
}
