"use client";

import {
  listSuites,
  getRepositorySummary,
  listCustomFieldDefinitions,
  getProjectDashboardSummary,
  getReportsOverview,
  getReportsInsights,
  getRequirementsSummary,
  getZyraAgent,
  listProjectsOverview,
} from "@/lib/api";
import { getPageCache, setPageCache, invalidatePageCache } from "@/lib/pageDataCache";

/**
 * Refetches one page's cached snapshot in the background and merges the result on top of whatever
 * is already there — only when that page has actually been cached this session. getPageCache
 * returns undefined for a page nobody has opened yet in this tab, and that page's own first mount
 * always does a real fetch regardless of any of this (see pageDataCache.ts), so there is nothing
 * stale to correct. Falls back to dropping the entry if the refetch itself fails, so a stale
 * snapshot is never left looking current.
 */
async function patchPageCacheIfCached<T extends object>(key: string, fetchPatch: () => Promise<Partial<T>>): Promise<void> {
  const existing = getPageCache<T>(key);
  if (!existing) return;
  try {
    const patch = await fetchPatch();
    setPageCache<T>(key, { ...existing, ...patch });
  } catch {
    invalidatePageCache(key);
  }
}

/**
 * Every page whose pageDataCache snapshot includes a test-case-derived count, list, or summary —
 * repository totals, suite counts, coverage %, requirement-linkage counts, "generated by Zyra"
 * stats — goes stale the moment Zyra saves new test cases into the repository, the same way the
 * Test Cases page itself did (see ZyraChatReviewPanel.tsx, the original fix this generalizes).
 * Fired in the background right when a save succeeds, one call per affected module, so each is
 * already correct by the time the user actually navigates there instead of blocking on a fetch.
 *
 * Pages whose cache carries no test-case data — bugs, plans (`caseCount` is a plan_items
 * assignment, not a live repository rollup), knowledge base, cycles (per-run execution snapshots),
 * activity — are deliberately left untouched.
 */
export function refreshPageCachesAfterZyraSave(projectId: string, workspaceId: string | undefined): void {
  void patchPageCacheIfCached(`testcases:${projectId}`, async () => ({
    suites: await listSuites(projectId),
    repoSummary: await getRepositorySummary(projectId).catch(() => null),
    customFieldDefinitions: await listCustomFieldDefinitions(projectId, { statuses: ["active"] }).catch(() => []),
  }));

  void patchPageCacheIfCached(`dashboard:${projectId}`, async () => ({
    summary: await getProjectDashboardSummary(projectId),
  }));

  void patchPageCacheIfCached(`reports:${projectId}`, async () => {
    const [overview, insights] = await Promise.all([getReportsOverview(projectId), getReportsInsights(projectId)]);
    return { overview, insights };
  });

  void patchPageCacheIfCached(`reports:${projectId}:execFilters`, async () => ({
    suites: await listSuites(projectId),
  }));

  void patchPageCacheIfCached(`requirements:${projectId}`, async () => ({
    summary: await getRequirementsSummary(projectId),
  }));

  // Tasks and Settings both cache the same ZyraAgentState shape (testcasesCreated is the field
  // that goes stale) — one fetch feeds both patches instead of hitting the endpoint twice, and
  // only fires at all if at least one of the two has actually been cached this session.
  const tasksKey = `agents-tasks:${projectId}`;
  const settingsKey = `agents-zyra-settings:${projectId}`;
  if (getPageCache(tasksKey) || getPageCache(settingsKey)) {
    const agentState = getZyraAgent(projectId);
    void patchPageCacheIfCached(tasksKey, async () => ({ state: await agentState }));
    void patchPageCacheIfCached(settingsKey, async () => ({ state: await agentState }));
  }

  // Not keyed per-project — the workspace Projects list caches every project's overview
  // (testCaseCount/suiteCount included) as one array, so there is no per-field patch to make,
  // only a full refetch of the same shape that page's own loadData writes.
  const overviewKey = `projects:overview:${workspaceId ?? "default"}`;
  if (getPageCache(overviewKey)) {
    void listProjectsOverview()
      .then((overview) => setPageCache(overviewKey, overview))
      .catch(() => invalidatePageCache(overviewKey));
  }
}
