apiVersion: v1
kind: Service
metadata:
  name: tesbo-automation-agent
  labels:
    app: tesbo-automation-agent
spec:
  selector:
    app: tesbo-automation-agent
  ports:
    - name: http
      port: 7400
      targetPort: http
  type: ClusterIP
