apiVersion: v1
kind: Service
metadata:
  name: automation-api
  namespace: bettercases-automation
spec:
  selector:
    app: automation-api
  ports:
    - name: http
      port: 7400
      targetPort: 7400
