apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: redis-trigger-auth
  namespace: bettercases-automation
spec:
  secretTargetRef:
    - parameter: password
      name: automation-secrets
      key: redis-password
