apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: automation-worker
  namespace: bettercases-automation
spec:
  scaleTargetRef:
    name: automation-worker
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 50
  triggers:
    - type: redis
      metadata:
        address: REDIS_ADDRESS_REPLACE_ME
        listName: bull:automation-execution-jobs:wait
        listLength: "2"
